language: go

go:
  - 1.5.2
  - tip

install:
  go get github.com/tools/godep
  godep go build -o bin/warden-agent ./warden-agent/
  godep go build -o bin/warden-guardian ./warden-guardian/
  godep go build -o bin/warden-template ./warden-template/